config/routes.rb
Rails.application.routes.draw do
 
  # FRONTEND
  devise_for :users
  root to: "welcome#index"
  # BACKEND
   namespace :admin do
    root 'dashboard#index'
    resources :games
    resources :genres
    resources :platforms
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
	belongs_to :genre
	belongs_to :platform
end

app/models/genre.rb
class Genre < ActiveRecord::Base
	has_many :games
end

app/models/platform.rb
class Platform < ActiveRecord::Base
	validates :name, presence: true
	has_many :games
end

app/models/post.rb
class Post < ActiveRecord::Base
has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
	layout 'admin'
	before_filter :authenticate_user!
	before_filter :deny_access_to_unauthorized_users

	def deny_access_to_unauthorized_users
  	redirect_to root_path, alert: "Acceso no autorizado" if !current_user.admin?
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
	def index
	end
end

app/controllers/admin/games_controller.rb
class Admin::GamesController < Admin::BaseController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:title, :summary, :description, :developer, :publishing_date)
    end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < Admin::BaseController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:name, :description)
    end
end

app/controllers/admin/platforms_controller.rb
class Admin::PlatformsController < Admin::BaseController
  before_action :set_platform, only: [:show, :edit, :update, :destroy]

  def index
    @platforms = Platform.all
  end

  def show
  end

  def new
    @platform = Platform.new
  end

  def edit
  end

  def create
    @platform = Platform.new(platform_params)
    if @platform.save
      redirect_to @platform, notice: 'Platform was successfully created.'
    else
      render :new
    end
  end

  def update
    if @platform.update(platform_params)
      redirect_to @platform, notice: 'Platform was successfully updated.' 
    else
      render :edit 
    end
  end

  def destroy
    @platform.destroy
    redirect_to platforms_url, notice: 'Platform was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_platform
      @platform = Platform.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def platform_params
      params.require(:platform).permit(:name, :description)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/dashboard/index.html.erb
PANEL ADMINISTRACION

app/views/admin/games/_form.html.erb
<%= form_for([:admin, @game]) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_field :summary %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :developer %><br>
    <%= f.text_field :developer %>
  </div>
  <div class="field">
    <%= f.label :publishing_date %><br>
    <%= f.date_select :publishing_date %>
  </div>
  <div class="field">
    <%= f.label :genre_id %><br>
    <%= f.collection_select :genre_id, Genre.all, :id, :name %>
  </div>  
    <div class="field">
    <%= f.label :platform_id %><br>
    <%= f.collection_select :platforms_id, Platform.all, :id, :name %>
  </div>  
  <div class="actions"










































Ç   <%= f.submit %>
  </div>
<% end %>

app/views/admin/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @game] %> |
<%= link_to 'Back', admin_games_path %>

app/views/admin/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Games</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Summary</th>
      <th>Description</th>
      <th>Developer</th>
      <th>Publishing date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.title %></td>
        <td><%= game.summary %></td>
        <td><%= game.description %></td>
        <td><%= game.developer %></td>
        <td><%= game.publishing_date %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Juego Nuevo', new_admin_game_path %>

app/views/admin/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_games_path %>

app/views/admin/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @game.title %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @game.summary %>
</p>

<p>
  <strong>Description:</strong>
  <%= @game.description %>
</p>

<p>
  <strong>Developer:</strong>
  <%= @game.developer %>
</p>

<p>
  <strong>Publishing date:</strong>
  <%= @game.publishing_date %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/admin/genres/_form.html.erb
<%= form_for(@genre) do |f| %>
  <% if @genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% @genre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/genres/edit.html.erb
<h1>Editing Genre</h1>

<%= render 'form' %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

app/views/admin/genres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Genres</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td><%= genre.name %></td>
        <td><%= genre.description %></td>
        <td><%= link_to 'Show', genre %></td>
        <td><%= link_to 'Edit', edit_genre_path(genre) %></td>
        <td><%= link_to 'Destroy', genre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Genre', new_genre_path %>

app/views/admin/genres/new.html.erb
<h1>New Genre</h1>

<%= render 'form' %>

<%= link_to 'Back', genres_path %>

app/views/admin/genres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @genre.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @genre.description %>
</p>

<%= link_to 'Edit', edit_genre_path(@genre) %> |
<%= link_to 'Back', genres_path %>

app/views/admin/platforms/_form.html.erb
<%= form_for(@platform) do |f| %>
  <% if @platform.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@platform.errors.count, "error") %> prohibited this platform from being saved:</h2>

      <ul>
      <% @platform.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/platforms/edit.html.erb
<h1>Editing Platform</h1>

<%= render 'form' %>

<%= link_to 'Show', @platform %> |
<%= link_to 'Back', platforms_path %>

app/views/admin/platforms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Platforms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @platforms.each do |platform| %>
      <tr>
        <td><%= platform.name %></td>
        <td><%= platform.description %></td>
        <td><%= link_to 'Show', platform %></td>
        <td><%= link_to 'Edit', edit_platform_path(platform) %></td>
        <td><%= link_to 'Destroy', platform, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Platform', new_platform_path %>

app/views/admin/platforms/new.html.erb
<h1>New Platform</h1>

<%= render 'form' %>

<%= link_to 'Back', platforms_path %>

app/views/admin/platforms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @platform.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @platform.description %>
</p>

<%= link_to 'Edit', edit_platform_path(@platform) %> |
<%= link_to 'Back', platforms_path %>

app/views/admin/shared/_header.html.erb
<ul>
	<li>INICIO</li>
	<li><%= link_to "JUEGOS", admin_games_path %></li>
	<li>GENEROS</li>
	<li>PLATAFORMAS</li>
	<li>OFERTAS</li>
</ul>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin - Gamelytics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= render 'admin/shared/header'%>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gamelytics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
hola
<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>
<% if user_signed_in? %>
  <li>
  <%= link_to('Edit registration', edit_user_registration_path) %>
  </li>
<% else %>
  <li>
  <%= link_to('Register', new_user_registration_path)  %>
  </li>
<% end %>